name: .NET Build

on:
  push:
      paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'
  pull_request:
      paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'
  workflow_dispatch:

jobs:
  build:
    name: .NET on ${{ matrix.runs-on }} (${{ matrix.configuration }})
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [windows-latest]
        configuration: [Debug]
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Publish
      run: dotnet build -c ${{ matrix.configuration }}
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: FMT-Build-${{ matrix.configuration }}
        path: UI\FMT\bin\${{ matrix.configuration }}\net7.0-windows\
        if-no-files-found: error